[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = [
    "arboles_info_project/__version__.py:__version__",
    "pyproject.toml:version"
]
tag_format = "v$version"
bump_message = """chore(release): bump version $current_version → $new_version

[skip ci]"""
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
# changelog_start_rev se calculará automáticamente desde el primer commit si no hay tags
major_version_zero = true

